name: vapatinagy
channels:
  - conda-forge
dependencies:
  - python
  - spacy
  - pandas
  - numpy
  - conda:
    - pandas
    - numpy
    - spacy
    - spacy:
      - de_core_news_sm
      - de_core_news_md
